name: littlepurplemen
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9940012847073376
title: Little Purple Men
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#011121'
    - '#032c58'
    - '#096fc1'
    - '#416388'
    - '#08d0e0'
  brandStrength: 0.7451596015598625
  lightness: 0.2865797465201467
  saturation: 0.15797966672107577
  rhythmicContrast: 0.3544519005808979
purpose: []
